name: Test and Publish

on:
  push:
    branches:
      - "master"
      - "branch*"
  pull_request:
    branches:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish"

    environment: cargo

    permissions:
      contents: write

    env:
      TAG_PREFIX: v

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check fmt
        run: cargo fmt --check

      # v0.1.15 目前版本
      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ runner.os }}-build-v0.2.2

      - name: Show cargo info
        run: cargo version --verbose

      - name: Run publish-action of oss
        id: publish
        uses: tu6ge/publish-action@v0.6.0-beta1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          DIR: "/"
          TAG_PREFIX: ${{ env.TAG_PREFIX }}

      - name: Generate changelog (git-cliff)
        if: github.event_name != 'pull_request' && steps.publish.outputs.publish == 'true'
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: -vv --latest --strip header
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: RELEASE_NOTES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release
        if: github.event_name != 'pull_request' && steps.publish.outputs.publish == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_PREFIX }}${{ steps.publish.outputs.new_version_value }}
          name: ${{ env.TAG_PREFIX }}${{ steps.publish.outputs.new_version_value }}
          body_path: ${{ steps.git-cliff.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
